# Make sure to edit this file within src/cfg/travis.yml to ensure that your modifications are not overwritten by the build.

language: java
jdk:
  - openjdk7

before_script:
  - mkdir workspace
  - mkdir workspace/AppEngineSDK
  - cd workspace/AppEngineSDK
  - wget http://googleappengine.googlecode.com/files/appengine-java-sdk-1.8.1.1.zip
  - unzip appengine-java-sdk-1.8.1.1.zip
  - cd ../..
  - export ANT_OPTS=-javaagent:$HOME/build/LucidTechnics/Airlift/workspace/AppEngineSDK/appengine-java-sdk-1.8.1.1/lib/agent/app-engine-agent.jar
  - export AIRLIFT_APP_ENGINE_DEV_HOME=$HOME/build/LucidTechnics/Airlift/workspace/AppEngineSDK/appengine-java-sdk-1.8.1.1

# whitelist
branches:
  only:
    - master
    - airlift_2.0_development
    - testEnhance
    - testEnhance2

notifications:
  email:
    - ci@lucidtechnics.com
