var $appName$;

if (!$appName$)
{
	$appName$ = {};
}
else if (typeof $appName$ != "object")
{
	throw new Error("$appName$ already exists and it is not an object");
}

/**
 * Here are all the JavaScript constructors for the domain objects in the
 * $appName$ domain
 **/

$appNameMethod, domainName: { a, d | $a$["$d$"] = function() \{ return airlift.ar("$d$"); \}; }; separator="\n"$


