$className$Validator.validate$propertyName$ = function(_value)
{
	var errorArray = [];
	var message;
	var parameters;

	LOG.info("Validating property: $propertyName$ on domain: $className$ with value: " + _value);

	$requiredValidationFunction$

	if (_value !== null && _value !== undefined && "" !== _value)
	{
		LOG.info("property value is not null, not undefined, && not empty string");
		$validationFunctionInnards; separator="\n\n"$
	}

	return errorArray;
}