exports.person = function(_id, _fullName, _status, _birthDate, _age)
{
	var context = {};
	
	context.resourceName = 'person';

	//person resource metadata generated by AirliftLabs Person dictation ...
	context.resourceMetadata = require('airlift/ResourceMetadata').create({ persistable:true, securable:true, presentable:true });
	context.resourceMetadata.name = 'person';
	context.resourceMetadata.attributes = ['fullName', 'shortName', 'status', 'birthDate', 'age', 'friendList', 'familySet', 'auditPostDate', 'auditPutDate', 'auditUserId', 'id'];

	//must be the same as context.resourceMetadata.attributes to test
	//map functionality.
	context.attributesMap = {'fullName': 1, 'shortName': 1, 'status': 1, 'birthDate': 1, 'age': 1, 'friendList': 1, 'familySet': 1, 'auditPostDate': 1, 'auditPutDate': 1, 'auditUserId': 1, 'id': 1};

	//person attributes metadata generated by Airlift Labs Person
	//dictation
	var MetaData = function()
	{
		this.resourceName = 'person';
		this.attributes = {};
		this.foreignKeys = [];

		this.attributes['fullName'] = require('airlift/AttributeMetadata').create({ name:"fullName", type:"java.lang.String", isIndexable:true, displayOrder:10, label:"full name" }); 
		this.attributes['shortName'] = require('airlift/AttributeMetadata').create({ name:"shortName", type:"java.lang.String", isIndexable:true, displayOrder:20, label:"short name" }); 
		this.attributes['status'] = require('airlift/AttributeMetadata').create({ name:"status", type:"java.lang.String", displayOrder:30, label:"status", allowedValues:{ "senior": 1,"middle aged": 1,"youth": 1 } }); 
		this.attributes['birthDate'] = require('airlift/AttributeMetadata').create({ name:"birthDate", type:"java.util.Date", isIndexable:true, displayOrder:40, label:"birth date" }); 
		this.attributes['age'] = require('airlift/AttributeMetadata').create({ minValue: 18, maxValue: 110, name:"age", type:"java.lang.Integer", isIndexable:true, displayOrder:50, label:"age" }); 
		this.attributes['friendList'] = require('airlift/AttributeMetadata').create({ name:"friendList", type:"java.util.List<java.lang.String>", isIndexable:true, displayOrder:60, label:"friend list" }); 
		this.attributes['familySet'] = require('airlift/AttributeMetadata').create({ name:"familySet", type:"java.util.Set<java.lang.String>", isIndexable:true, displayOrder:70, label:"family set" }); 
		this.attributes['auditPostDate'] = require('airlift/AttributeMetadata').create({ name:"auditPostDate", type:"java.util.Date", isSearchable:true, isIndexable:true, required:false, label:"record created date" }); 
		this.attributes['auditPutDate'] = require('airlift/AttributeMetadata').create({ name:"auditPutDate", type:"java.util.Date", isSearchable:true, isIndexable:true, required:false, label:"record updated date" }); 
		this.attributes['auditUserId'] = require('airlift/AttributeMetadata').create({ name:"auditUserId", type:"java.lang.String", required:false, label:"changed by user id", isPresentable:false }); 
		this.attributes['id'] = require('airlift/AttributeMetadata').create({ name:"id", type:"java.lang.String", isPrimaryKey:true, displayOrder:0, label:"record id" }); 
	}

	context.attributesMetadata = new MetaData();
	context.attributes = context.resourceMetadata.attributes;
	context.WEB_CONTEXT;

	return context;
};