<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
	<base href="$base$" />
	<title>$title$</title>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
	
	<link rel="stylesheet" href="css/bluetrip/css/screen.css" type="text/css" media="screen, projection" />
   	<link rel="stylesheet" href="css/bluetrip/css/print.css" type="text/css" media="print" /> 
		
	<!--[if IE]>
		<link rel="stylesheet" href="css/bluetrip/css/ie.css" type="text/css" media="screen, projection" />
	<![endif]-->
	
   	<link rel="stylesheet" href="css/bluetrip/css/style.css" type="text/css" media="screen, projection" />

</head>

<body>
   <div class="container $showgrid$">
	  <div class="span-23 header last">
		 <hl class="headercaps">$appName$</h1>
	  </div>

	  <div class="span-4 sidebar">
		$left$
	  </div>

	  <div class="span-14 sidebar">
		 $middle$
	  </div>

	  <div class="span-4 sidebar last">
		 $right$
	  </div>
   </div> <!-- end .container -->
</body>
</html>